"""Initial schema

Revision ID: 1bc7f0a7982d
Revises: 
Create Date: 2026-07-06 07:06:16.405944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bc7f0a7982d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvalticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ticket_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_required', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvalticket_request_id'), 'approvalticket', ['request_id'], unique=False)
    op.create_index(op.f('ix_approvalticket_tenant_id'), 'approvalticket', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_approvalticket_ticket_id'), 'approvalticket', ['ticket_id'], unique=True)
    op.create_table('automationlock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lock_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automationlock_lock_name'), 'automationlock', ['lock_name'], unique=False)
    op.create_index(op.f('ix_automationlock_tenant_id'), 'automationlock', ['tenant_id'], unique=False)
    op.create_table('erpsynclog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sync_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('erp_document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('erp_document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('erp_response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erpsynclog_idempotency_key'), 'erpsynclog', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_erpsynclog_request_id'), 'erpsynclog', ['request_id'], unique=False)
    op.create_index(op.f('ix_erpsynclog_sync_id'), 'erpsynclog', ['sync_id'], unique=True)
    op.create_index(op.f('ix_erpsynclog_tenant_id'), 'erpsynclog', ['tenant_id'], unique=False)
    op.create_table('goldensample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sample_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corrected_parts_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corrected_vehicle_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correction_reason_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goldensample_request_id'), 'goldensample', ['request_id'], unique=False)
    op.create_index(op.f('ix_goldensample_sample_id'), 'goldensample', ['sample_id'], unique=True)
    op.create_index(op.f('ix_goldensample_tenant_id'), 'goldensample', ['tenant_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('items_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoice_request_id'), 'invoice', ['request_id'], unique=False)
    op.create_index(op.f('ix_invoice_tenant_id'), 'invoice', ['tenant_id'], unique=False)
    op.create_table('jobrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('events_emitted', sa.Integer(), nullable=False),
    sa.Column('requests_processed', sa.Integer(), nullable=False),
    sa.Column('requests_skipped', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobrun_job_id'), 'jobrun', ['job_id'], unique=False)
    op.create_index(op.f('ix_jobrun_job_name'), 'jobrun', ['job_name'], unique=False)
    op.create_index(op.f('ix_jobrun_tenant_id'), 'jobrun', ['tenant_id'], unique=False)
    op.create_table('llmusagelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llmusagelog_correlation_id'), 'llmusagelog', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_llmusagelog_job_run_id'), 'llmusagelog', ['job_run_id'], unique=False)
    op.create_index(op.f('ix_llmusagelog_request_id'), 'llmusagelog', ['request_id'], unique=False)
    op.create_index(op.f('ix_llmusagelog_tenant_id'), 'llmusagelog', ['tenant_id'], unique=False)
    op.create_table('matchevidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('catalog_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('oem_exact_score', sa.Float(), nullable=False),
    sa.Column('brand_article_score', sa.Float(), nullable=False),
    sa.Column('normalized_name_score', sa.Float(), nullable=False),
    sa.Column('vehicle_compatibility_score', sa.Float(), nullable=False),
    sa.Column('side_position_score', sa.Float(), nullable=False),
    sa.Column('quantity_pack_score', sa.Float(), nullable=False),
    sa.Column('language_synonym_score', sa.Float(), nullable=False),
    sa.Column('historical_acceptance_score', sa.Float(), nullable=False),
    sa.Column('supplier_data_quality_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matched_fields_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conflicts_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchevidence_evidence_id'), 'matchevidence', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_matchevidence_part_intent_id'), 'matchevidence', ['part_intent_id'], unique=False)
    op.create_index(op.f('ix_matchevidence_request_id'), 'matchevidence', ['request_id'], unique=False)
    op.create_index(op.f('ix_matchevidence_tenant_id'), 'matchevidence', ['tenant_id'], unique=False)
    op.create_table('outboundmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outboundmessage_idempotency_key'), 'outboundmessage', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_outboundmessage_request_id'), 'outboundmessage', ['request_id'], unique=False)
    op.create_index(op.f('ix_outboundmessage_tenant_id'), 'outboundmessage', ['tenant_id'], unique=False)
    op.create_table('partrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_phone_masked', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_email_masked', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_erp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_vin_masked', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_make', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_generation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('vehicle_engine', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_confidence', sa.Float(), nullable=True),
    sa.Column('vin_validity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parts_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_evidence_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pricing_evidence_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('margin_policy_passed', sa.Boolean(), nullable=True),
    sa.Column('erp_quotation_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('erp_invoice_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('erp_payment_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audit_chain_complete', sa.Boolean(), nullable=False),
    sa.Column('raw_input_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tracking_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tracking_token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partrequest_idempotency_key'), 'partrequest', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_partrequest_request_id'), 'partrequest', ['request_id'], unique=True)
    op.create_index(op.f('ix_partrequest_tenant_id'), 'partrequest', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_partrequest_tracking_token'), 'partrequest', ['tracking_token'], unique=True)
    op.create_table('pricehistoryledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('catalog_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricehistoryledger_catalog_id'), 'pricehistoryledger', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_pricehistoryledger_tenant_id'), 'pricehistoryledger', ['tenant_id'], unique=False)
    op.create_table('requestevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evidence_refs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('previous_event_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requestevent_event_id'), 'requestevent', ['event_id'], unique=True)
    op.create_index(op.f('ix_requestevent_request_id'), 'requestevent', ['request_id'], unique=False)
    op.create_index(op.f('ix_requestevent_tenant_id'), 'requestevent', ['tenant_id'], unique=False)
    op.create_table('requestscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('field_completeness', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('duplicate_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('supplier_score', sa.Float(), nullable=True),
    sa.Column('margin_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('weak_match_risk', sa.Boolean(), nullable=True),
    sa.Column('supplier_risk', sa.Boolean(), nullable=True),
    sa.Column('return_risk', sa.Boolean(), nullable=True),
    sa.Column('low_margin_risk', sa.Boolean(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requestscore_request_id'), 'requestscore', ['request_id'], unique=False)
    op.create_index(op.f('ix_requestscore_tenant_id'), 'requestscore', ['tenant_id'], unique=False)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('avg_delivery_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating_manual', sa.Float(), nullable=True),
    sa.Column('rating_auto', sa.Float(), nullable=False),
    sa.Column('account_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes_internal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_feed_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_status'), 'supplier', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_supplier_id'), 'supplier', ['supplier_id'], unique=True)
    op.create_index(op.f('ix_supplier_tenant_id'), 'supplier', ['tenant_id'], unique=False)
    op.create_table('supplieractivitylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplieractivitylog_event_id'), 'supplieractivitylog', ['event_id'], unique=True)
    op.create_index(op.f('ix_supplieractivitylog_event_type'), 'supplieractivitylog', ['event_type'], unique=False)
    op.create_index(op.f('ix_supplieractivitylog_supplier_id'), 'supplieractivitylog', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplieractivitylog_table_id'), 'supplieractivitylog', ['table_id'], unique=False)
    op.create_index(op.f('ix_supplieractivitylog_tenant_id'), 'supplieractivitylog', ['tenant_id'], unique=False)
    op.create_table('suppliercatalogitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('catalog_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oem_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliercatalogitem_catalog_id'), 'suppliercatalogitem', ['catalog_id'], unique=True)
    op.create_index(op.f('ix_suppliercatalogitem_supplier_id'), 'suppliercatalogitem', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_suppliercatalogitem_tenant_id'), 'suppliercatalogitem', ['tenant_id'], unique=False)
    op.create_table('supplieroffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('offer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplieroffer_offer_id'), 'supplieroffer', ['offer_id'], unique=False)
    op.create_index(op.f('ix_supplieroffer_request_id'), 'supplieroffer', ['request_id'], unique=False)
    op.create_index(op.f('ix_supplieroffer_tenant_id'), 'supplieroffer', ['tenant_id'], unique=False)
    op.create_table('supplierreliabilitylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplierreliabilitylog_supplier_id'), 'supplierreliabilitylog', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplierreliabilitylog_tenant_id'), 'supplierreliabilitylog', ['tenant_id'], unique=False)
    op.create_table('suppliertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('mapped_columns_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validation_summary_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliertable_is_active'), 'suppliertable', ['is_active'], unique=False)
    op.create_index(op.f('ix_suppliertable_status'), 'suppliertable', ['status'], unique=False)
    op.create_index(op.f('ix_suppliertable_supplier_id'), 'suppliertable', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_suppliertable_table_id'), 'suppliertable', ['table_id'], unique=True)
    op.create_index(op.f('ix_suppliertable_tenant_id'), 'suppliertable', ['tenant_id'], unique=False)
    op.create_table('suppliertablerow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oem_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliertablerow_row_key'), 'suppliertablerow', ['row_key'], unique=False)
    op.create_index(op.f('ix_suppliertablerow_supplier_id'), 'suppliertablerow', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_suppliertablerow_table_id'), 'suppliertablerow', ['table_id'], unique=False)
    op.create_index(op.f('ix_suppliertablerow_tenant_id'), 'suppliertablerow', ['tenant_id'], unique=False)
    op.create_table('uploadartifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('safe_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_mime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploadartifact_artifact_id'), 'uploadartifact', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_uploadartifact_request_id'), 'uploadartifact', ['request_id'], unique=False)
    op.create_index(op.f('ix_uploadartifact_sha256'), 'uploadartifact', ['sha256'], unique=False)
    op.create_index(op.f('ix_uploadartifact_tenant_id'), 'uploadartifact', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploadartifact_tenant_id'), table_name='uploadartifact')
    op.drop_index(op.f('ix_uploadartifact_sha256'), table_name='uploadartifact')
    op.drop_index(op.f('ix_uploadartifact_request_id'), table_name='uploadartifact')
    op.drop_index(op.f('ix_uploadartifact_artifact_id'), table_name='uploadartifact')
    op.drop_table('uploadartifact')
    op.drop_index(op.f('ix_suppliertablerow_tenant_id'), table_name='suppliertablerow')
    op.drop_index(op.f('ix_suppliertablerow_table_id'), table_name='suppliertablerow')
    op.drop_index(op.f('ix_suppliertablerow_supplier_id'), table_name='suppliertablerow')
    op.drop_index(op.f('ix_suppliertablerow_row_key'), table_name='suppliertablerow')
    op.drop_table('suppliertablerow')
    op.drop_index(op.f('ix_suppliertable_tenant_id'), table_name='suppliertable')
    op.drop_index(op.f('ix_suppliertable_table_id'), table_name='suppliertable')
    op.drop_index(op.f('ix_suppliertable_supplier_id'), table_name='suppliertable')
    op.drop_index(op.f('ix_suppliertable_status'), table_name='suppliertable')
    op.drop_index(op.f('ix_suppliertable_is_active'), table_name='suppliertable')
    op.drop_table('suppliertable')
    op.drop_index(op.f('ix_supplierreliabilitylog_tenant_id'), table_name='supplierreliabilitylog')
    op.drop_index(op.f('ix_supplierreliabilitylog_supplier_id'), table_name='supplierreliabilitylog')
    op.drop_table('supplierreliabilitylog')
    op.drop_index(op.f('ix_supplieroffer_tenant_id'), table_name='supplieroffer')
    op.drop_index(op.f('ix_supplieroffer_request_id'), table_name='supplieroffer')
    op.drop_index(op.f('ix_supplieroffer_offer_id'), table_name='supplieroffer')
    op.drop_table('supplieroffer')
    op.drop_index(op.f('ix_suppliercatalogitem_tenant_id'), table_name='suppliercatalogitem')
    op.drop_index(op.f('ix_suppliercatalogitem_supplier_id'), table_name='suppliercatalogitem')
    op.drop_index(op.f('ix_suppliercatalogitem_catalog_id'), table_name='suppliercatalogitem')
    op.drop_table('suppliercatalogitem')
    op.drop_index(op.f('ix_supplieractivitylog_tenant_id'), table_name='supplieractivitylog')
    op.drop_index(op.f('ix_supplieractivitylog_table_id'), table_name='supplieractivitylog')
    op.drop_index(op.f('ix_supplieractivitylog_supplier_id'), table_name='supplieractivitylog')
    op.drop_index(op.f('ix_supplieractivitylog_event_type'), table_name='supplieractivitylog')
    op.drop_index(op.f('ix_supplieractivitylog_event_id'), table_name='supplieractivitylog')
    op.drop_table('supplieractivitylog')
    op.drop_index(op.f('ix_supplier_tenant_id'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_supplier_id'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_status'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_requestscore_tenant_id'), table_name='requestscore')
    op.drop_index(op.f('ix_requestscore_request_id'), table_name='requestscore')
    op.drop_table('requestscore')
    op.drop_index(op.f('ix_requestevent_tenant_id'), table_name='requestevent')
    op.drop_index(op.f('ix_requestevent_request_id'), table_name='requestevent')
    op.drop_index(op.f('ix_requestevent_event_id'), table_name='requestevent')
    op.drop_table('requestevent')
    op.drop_index(op.f('ix_pricehistoryledger_tenant_id'), table_name='pricehistoryledger')
    op.drop_index(op.f('ix_pricehistoryledger_catalog_id'), table_name='pricehistoryledger')
    op.drop_table('pricehistoryledger')
    op.drop_index(op.f('ix_partrequest_tracking_token'), table_name='partrequest')
    op.drop_index(op.f('ix_partrequest_tenant_id'), table_name='partrequest')
    op.drop_index(op.f('ix_partrequest_request_id'), table_name='partrequest')
    op.drop_index(op.f('ix_partrequest_idempotency_key'), table_name='partrequest')
    op.drop_table('partrequest')
    op.drop_index(op.f('ix_outboundmessage_tenant_id'), table_name='outboundmessage')
    op.drop_index(op.f('ix_outboundmessage_request_id'), table_name='outboundmessage')
    op.drop_index(op.f('ix_outboundmessage_idempotency_key'), table_name='outboundmessage')
    op.drop_table('outboundmessage')
    op.drop_index(op.f('ix_matchevidence_tenant_id'), table_name='matchevidence')
    op.drop_index(op.f('ix_matchevidence_request_id'), table_name='matchevidence')
    op.drop_index(op.f('ix_matchevidence_part_intent_id'), table_name='matchevidence')
    op.drop_index(op.f('ix_matchevidence_evidence_id'), table_name='matchevidence')
    op.drop_table('matchevidence')
    op.drop_index(op.f('ix_llmusagelog_tenant_id'), table_name='llmusagelog')
    op.drop_index(op.f('ix_llmusagelog_request_id'), table_name='llmusagelog')
    op.drop_index(op.f('ix_llmusagelog_job_run_id'), table_name='llmusagelog')
    op.drop_index(op.f('ix_llmusagelog_correlation_id'), table_name='llmusagelog')
    op.drop_table('llmusagelog')
    op.drop_index(op.f('ix_jobrun_tenant_id'), table_name='jobrun')
    op.drop_index(op.f('ix_jobrun_job_name'), table_name='jobrun')
    op.drop_index(op.f('ix_jobrun_job_id'), table_name='jobrun')
    op.drop_table('jobrun')
    op.drop_index(op.f('ix_invoice_tenant_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_request_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_goldensample_tenant_id'), table_name='goldensample')
    op.drop_index(op.f('ix_goldensample_sample_id'), table_name='goldensample')
    op.drop_index(op.f('ix_goldensample_request_id'), table_name='goldensample')
    op.drop_table('goldensample')
    op.drop_index(op.f('ix_erpsynclog_tenant_id'), table_name='erpsynclog')
    op.drop_index(op.f('ix_erpsynclog_sync_id'), table_name='erpsynclog')
    op.drop_index(op.f('ix_erpsynclog_request_id'), table_name='erpsynclog')
    op.drop_index(op.f('ix_erpsynclog_idempotency_key'), table_name='erpsynclog')
    op.drop_table('erpsynclog')
    op.drop_index(op.f('ix_automationlock_tenant_id'), table_name='automationlock')
    op.drop_index(op.f('ix_automationlock_lock_name'), table_name='automationlock')
    op.drop_table('automationlock')
    op.drop_index(op.f('ix_approvalticket_ticket_id'), table_name='approvalticket')
    op.drop_index(op.f('ix_approvalticket_tenant_id'), table_name='approvalticket')
    op.drop_index(op.f('ix_approvalticket_request_id'), table_name='approvalticket')
    op.drop_table('approvalticket')
    # ### end Alembic commands ###
